n = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...')
print(f'Seu nome em maiúsculas é {n.upper()}')
print(f'Seu nome em minúsculas é {n.lower()}')
print(f'Seu nome tem ao todo {(len(n) - n.count(" "))} letras')
print(f'Seu primeiro nome é {n[:n.find(" ")]} e ele tem {n.find(" ")} letras')
